NOT_YET_STARTED = 'NOT_YET_STARTED'
IN_PROGRESS = 'IN_PROGRESS'
COMPLETE = 'COMPLETE'
OTHER_AVAILABLE = 'OTHER_AVAILABLE'
OTHER_UNAVAILABLE = 'OTHER_UNAVAILABLE'

STRAIGHT_UP = 'SU'
AGAINST_THE_SPREAD = 'ATS'

HOME = 'H'
AWAY = 'A'
